const OWNER='jawa-dam',REPO='GEI-Research',BRANCH='main';
const API=`https://api.github.com/repos/${OWNER}/${REPO}/contents/data`;
const CATEGORIES=['chronology','civilizations','regions','texts','passages','cosmology','water','technology','linguistics','sources','evidence','comparisons','interpretations','hypotheses'];
const state={records:[],filtered:[],activeView:'explorer',edges:[],selectedId:null,graphZoom:1,graphPanX:0,graphPanY:0,trace:[]};
const $=id=>document.getElementById(id);
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titleCase=(s='')=>s.replace(/[-_]/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const typeLabel=t=>titleCase(t);
const confidenceOf=r=>r.confidence||r.confidence_level||r.confidence_code||'';
const evidenceOf=r=>r.evidence_level||r.evidence||'';
const descriptionOf=r=>r.description||r.summary||r.notes||'No description recorded.';
async function fetchJson(url){const x=await fetch(url,{headers:{Accept:'application/vnd.github+json'}});if(!x.ok)throw new Error(`${x.status} ${x.statusText}`);return x.json();}
async function loadDataset(){ $('status').textContent='Loading canonical records…'; const records=[]; for(const category of CATEGORIES){try{const listing=await fetchJson(`${API}/${category}?ref=${BRANCH}`);const files=listing.filter(x=>x.type==='file'&&x.name.endsWith('.json'));const loaded=await Promise.all(files.map(async f=>{try{return{...(await fetchJson(f.download_url)),_category:category,_path:f.path,_url:f.html_url};}catch(e){console.warn('Skipped',f.path,e);return null;}}));records.push(...loaded.filter(Boolean));}catch(e){console.warn(`Could not load ${category}`,e);}} state.records=records.sort((a,b)=>String(a.id).localeCompare(String(b.id)));state.edges=buildRelationships(state.records);populateFilters();applyFilters();$('status').textContent=`Canonical dataset connected · ${state.records.length} records · ${state.edges.length} relationships`;}
function populateFilters(){const types=[...new Set(state.records.map(r=>r.type).filter(Boolean))].sort();$('typeFilter').innerHTML='<option value="all">All types</option>'+types.map(t=>`<option value="${esc(t)}">${esc(typeLabel(t))}</option>`).join('');$('recordCount').textContent=state.records.length;$('typeCount').textContent=types.length;$('confidenceCount').textContent=state.records.filter(r=>confidenceOf(r)).length;}
function applyFilters(){const q=$('search').value.trim().toLowerCase(),type=$('typeFilter').value,status=$('statusFilter').value,conf=$('confidenceFilter').value;state.filtered=state.records.filter(r=>{const h=JSON.stringify(r).toLowerCase();return(!q||h.includes(q))&&(type==='all'||r.type===type)&&(status==='all'||r.status===status)&&(conf==='all'||confidenceOf(r)===conf);});$('resultCount').textContent=`${state.filtered.length} result${state.filtered.length===1?'':'s'}`;renderExplorer();renderTimeline();renderComparisons();renderEpistemic();renderGraph();renderIntelligence();}
function chips(r){const o=[`<span class="chip type">${esc(typeLabel(r.type))}</span>`];if(r.status)o.push(`<span class="chip">${esc(r.status)}</span>`);if(confidenceOf(r))o.push(`<span class="chip ${confidenceOf(r)==='C1'?'hyp':''}">${esc(confidenceOf(r))}</span>`);if(evidenceOf(r))o.push(`<span class="chip">${esc(evidenceOf(r))}</span>`);return o.join('');}
function renderExplorer(){const g=$('recordGrid');if(!state.filtered.length){g.innerHTML='<div class="record-card"><h3>No records found</h3><p>Try clearing a filter or using a broader search.</p></div>';return;}g.innerHTML=state.filtered.map(r=>`<article class="record-card" data-id="${esc(r.id)}"><div class="chips">${chips(r)}</div><h3>${esc(r.title||r.id)}</h3><p>${esc(descriptionOf(r).slice(0,190))}</p><div class="muted" style="margin-top:10px">${esc(r.id)}</div></article>`).join('');g.querySelectorAll('[data-id]').forEach(x=>x.addEventListener('click',()=>openRecord(x.dataset.id)));}
function parseStart(v){if(!v)return 9999999999999;const n=Number(String(v).replace(/[^0-9-]/g,''));if(!Number.isNaN(n)&&n)return n;const d=Date.parse(v);return Number.isNaN(d)?9999999999999:d;}
function renderTimeline(){const items=state.records.filter(r=>r.type==='chronology').slice().sort((a,b)=>parseStart(a.start)-parseStart(b.start));$('timeline').innerHTML=items.length?items.map(r=>`<div class="timeline-item"><div class="timeline-card" data-id="${esc(r.id)}"><div class="timeline-date">${esc(r.start||'UNKNOWN')} → ${esc(r.end||'UNKNOWN')}</div><h3>${esc(r.title)}</h3><p class="muted">${esc(descriptionOf(r).slice(0,220))}</p></div></div>`).join(''):'<div class="record-card"><p>No chronology records loaded.</p></div>';$('timeline').querySelectorAll('[data-id]').forEach(x=>x.addEventListener('click',()=>openRecord(x.dataset.id)));}
function renderComparisons(){const items=state.records.filter(r=>r.type==='comparison');$('comparisonCount').textContent=`${items.length} comparison${items.length===1?'':'s'}`;$('comparisonGrid').innerHTML=items.length?items.map(r=>`<article class="comparison-card" data-id="${esc(r.id)}"><div class="chips">${chips(r)}</div><h3>${esc(r.title)}</h3><p>${esc(descriptionOf(r).slice(0,260))}</p><div class="muted" style="margin-top:10px">${Array.isArray(r.subject_ids)?r.subject_ids.length:'—'} linked subjects</div></article>`).join(''):'<div class="record-card"><p>No comparison records loaded.</p></div>';$('comparisonGrid').querySelectorAll('[data-id]').forEach(x=>x.addEventListener('click',()=>openRecord(x.dataset.id)));}
function renderEpistemic(){const types=['source','evidence','comparison','interpretation','hypothesis'];$('epistemicCards').innerHTML=types.map(type=>{const rs=state.records.filter(r=>r.type===type),tone=type==='hypothesis'?'hyp':type==='interpretation'?'warn':'good';return`<div class="epistemic-card"><div class="chips"><span class="chip ${tone}">${esc(typeLabel(type))}</span></div><strong>${rs.length}</strong><p>canonical ${type}${rs.length===1?'':'s'} in the current dataset.</p></div>`;}).join('');}
const ID_FIELD_PATTERN=/(?:^|_)(ids?)$/i;
const RELATIONSHIP_EXCLUDE=new Set(['id','_path','_url']);
function relationLabel(field){const clean=field.replace(/_ids?$/i,'').replace(/_/g,' ');return clean||'reference';}
function buildRelationships(records){const byId=new Map(records.map(r=>[r.id,r])),edges=new Map();const add=(from,to,field)=>{if(!from||!to||from===to||!byId.has(to))return;const a=from<to?from:to,b=from<to?to:from,key=`${a}::${b}`;if(!edges.has(key))edges.set(key,{id:key,a,b,reasons:[]});const e=edges.get(key),reason=`${field} → ${relationLabel(field)}`;if(!e.reasons.includes(reason))e.reasons.push(reason);};records.forEach(r=>Object.entries(r).forEach(([field,value])=>{if(RELATIONSHIP_EXCLUDE.has(field)||!ID_FIELD_PATTERN.test(field))return;(Array.isArray(value)?value:[value]).filter(v=>typeof v==='string').forEach(id=>add(r.id,id,field));}));records.forEach(r=>{if(Array.isArray(r.subject_ids))r.subject_ids.forEach(id=>add(r.id,id,'subject_ids'));});return[...edges.values()].sort((a,b)=>a.a.localeCompare(b.a)||a.b.localeCompare(b.b));}
function visibleGraphData(){const ids=new Set(state.filtered.map(r=>r.id));return{nodes:state.filtered.slice(),edges:state.edges.filter(e=>ids.has(e.a)&&ids.has(e.b))};}
function graphDimensions(){const s=$('researchGraph');return{w:Math.max(s.clientWidth||700,320),h:Math.max(s.clientHeight||520,420)};}
function graphLayout(nodes,edges){const{w,h}=graphDimensions(),degree=new Map(nodes.map(r=>[r.id,0]));edges.forEach(e=>{degree.set(e.a,(degree.get(e.a)||0)+1);degree.set(e.b,(degree.get(e.b)||0)+1);});const sorted=nodes.slice().sort((a,b)=>(degree.get(b.id)||0)-(degree.get(a.id)||0)),cx=w/2,cy=h/2,r=Math.min(w,h)*.36,pos=new Map();sorted.forEach((x,i)=>{if(i===0)pos.set(x.id,{x:cx,y:cy});else{const ang=(i-1)/Math.max(1,nodes.length-1)*Math.PI*2-Math.PI/2,ring=r*(.62+.38*((i-1)%3)/2);pos.set(x.id,{x:cx+Math.cos(ang)*ring,y:cy+Math.sin(ang)*ring});}});return pos;}
function renderGraph(){const s=$('researchGraph');if(!s)return;const{nodes,edges}=visibleGraphData();$('graphCount').textContent=`${nodes.length} nodes · ${edges.length} relationships`;const pos=graphLayout(nodes,edges),{w,h}=graphDimensions();s.setAttribute('viewBox',`0 0 ${w} ${h}`);const eh=edges.map(e=>{const a=pos.get(e.a),b=pos.get(e.b);return`<line class="graph-edge" x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"></line>`;}).join('');const nh=nodes.map(r=>{const p=pos.get(r.id),sel=state.selectedId===r.id?' selected':'';return`<g class="graph-node${sel}" data-id="${esc(r.id)}" transform="translate(${p.x} ${p.y})"><circle r="${state.edges.filter(e=>e.a===r.id||e.b===r.id).length>3?18:14}"></circle><text y="29">${esc((r.title||r.id).slice(0,24))}</text><text class="node-type" y="42">${esc(typeLabel(r.type))}</text></g>`;}).join('');s.innerHTML=`<g transform="translate(${state.graphPanX} ${state.graphPanY}) scale(${state.graphZoom})">${eh}${nh}</g>`;s.querySelectorAll('.graph-node').forEach(n=>n.addEventListener('click',()=>selectGraphNode(n.dataset.id)));updateRelationshipTable(edges);renderGraphInspector(state.selectedId);}
function selectGraphNode(id){state.selectedId=id;renderGraph();}
function relatedFor(id){return state.edges.filter(e=>e.a===id||e.b===id).map(e=>({edge:e,other:e.a===id?e.b:e.a,record:state.records.find(r=>r.id===(e.a===id?e.b:e.a))})).filter(x=>x.record);}
function renderGraphInspector(id){if(!id){$('graphInspectorTitle').textContent='Select a record';$('graphInspectorText').textContent='Select a node to inspect its evidence-aware relationships.';$('relationshipList').innerHTML='';return;}const r=state.records.find(x=>x.id===id);if(!r)return;$('graphInspectorTitle').textContent=r.title||r.id;$('graphInspectorText').innerHTML=`${chips(r)} <span class="muted">${esc(r.id)}</span>`;const rel=relatedFor(id);$('relationshipList').innerHTML=rel.length?rel.map(x=>`<button class="relationship-item" data-id="${esc(x.record.id)}"><strong>${esc(x.record.title||x.record.id)}</strong><span>${esc(x.edge.reasons.join(' · '))}</span></button>`).join(''):'<p class="muted">No explicit references to another loaded record.</p>';$('relationshipList').querySelectorAll('[data-id]').forEach(x=>x.addEventListener('click',()=>selectGraphNode(x.dataset.id)));}
function updateRelationshipTable(edges){const rows=edges.map(e=>{const a=state.records.find(r=>r.id===e.a),b=state.records.find(r=>r.id===e.b);return`<tr><td><button data-id="${esc(e.a)}">${esc(a?.title||e.a)}</button><small>${esc(e.a)}</small></td><td>${esc(e.reasons.join(' · '))}</td><td><button data-id="${esc(e.b)}">${esc(b?.title||e.b)}</button><small>${esc(e.b)}</small></td></tr>`;}).join('');$('relationshipTable').innerHTML=rows?`<div class="table-scroll"><table><thead><tr><th>Record A</th><th>Explicit path</th><th>Record B</th></tr></thead><tbody>${rows}</tbody></table></div>`:'<div class="record-card"><p>No relationships exist among the currently filtered records.</p></div>';$('relationshipTable').querySelectorAll('[data-id]').forEach(x=>x.addEventListener('click',()=>selectGraphNode(x.dataset.id)));}
function traceFrom(id){const start=state.records.find(r=>r.id===id);if(!start)return[];const rank={hypothesis:0,interpretation:1,comparison:2,evidence:3,source:4,passage:4};const result=[],seen=new Set([id]),queue=[{id,depth:0}];while(queue.length&&result.length<30){const cur=queue.shift(),r=state.records.find(x=>x.id===cur.id);if(!r)continue;result.push({record:r,depth:cur.depth});const next=relatedFor(cur.id).sort((a,b)=>(rank[a.record.type]??8)-(rank[b.record.type]??8));next.forEach(x=>{if(!seen.has(x.record.id)){seen.add(x.record.id);queue.push({id:x.record.id,depth:cur.depth+1});}});}return result;}
function traceLabel(type){return{hypothesis:'HYPOTHESIS',interpretation:'INTERPRETATION',comparison:'COMPARISON',evidence:'EVIDENCE',source:'SOURCE',passage:'PASSAGE'}[type]||typeLabel(type).toUpperCase();}
function runTrace(id){state.trace=traceFrom(id);renderTrace();switchView('intelligence');}
function renderTrace(){const box=$('claimTrace');if(!state.trace.length){box.innerHTML='<div class="record-card"><p>Select a hypothesis, interpretation, evidence, or source and run a trace.</p></div>';return;}box.innerHTML=state.trace.map((x,i)=>`<div class="trace-step"><div class="trace-badge">${i+1}</div><div><span class="eyebrow">${esc(traceLabel(x.record.type))}</span><h3>${esc(x.record.title||x.record.id)}</h3><p>${esc(descriptionOf(x.record).slice(0,220))}</p><small>${esc(x.record.id)}${confidenceOf(x.record)?` · ${esc(confidenceOf(x.record))}`:''}${evidenceOf(x.record)?` · ${esc(evidenceOf(x.record))}`:''}</small></div></div>`).join('');}
function auditRecords(){const issues=[];const byId=new Map(state.records.map(r=>[r.id,r]));state.records.forEach(r=>{const refs=[];Object.entries(r).forEach(([field,value])=>{if(!ID_FIELD_PATTERN.test(field)||RELATIONSHIP_EXCLUDE.has(field))return;(Array.isArray(value)?value:[value]).filter(v=>typeof v==='string').forEach(id=>refs.push({field,id}));});if(['interpretation','hypothesis'].includes(r.type)&&!refs.some(x=>['evidence_ids','source_ids','subject_ids'].includes(x.field)))issues.push({severity:'warning',id:r.id,title:r.title||r.id,message:'No explicit evidence, source, or subject reference found.'});refs.forEach(x=>{if(!byId.has(x.id))issues.push({severity:'error',id:r.id,title:r.title||r.id,message:`Missing referenced record ${x.id} via ${x.field}.`});});if(r.type==='hypothesis'&&r.status==='confirmed')issues.push({severity:'error',id:r.id,title:r.title||r.id,message:'V1.x hypotheses cannot be marked confirmed.'});});return issues;}
function renderIntelligence(){const issues=auditRecords(),counts={error:issues.filter(x=>x.severity==='error').length,warning:issues.filter(x=>x.severity==='warning').length};$('auditSummary').textContent=`${counts.error} errors · ${counts.warning} warnings`;$('auditList').innerHTML=issues.length?issues.map(x=>`<button class="audit-item ${x.severity}" data-id="${esc(x.id)}"><span>${esc(x.severity.toUpperCase())}</span><strong>${esc(x.title)}</strong><p>${esc(x.message)}</p></button>`).join(''):'<div class="record-card"><h3>Epistemic audit clean</h3><p>No graph-level relationship or traceability issues detected in the currently loaded canonical dataset.</p></div>';$('auditList').querySelectorAll('[data-id]').forEach(x=>x.addEventListener('click',()=>{openRecord(x.dataset.id);state.selectedId=x.dataset.id;renderGraphInspector(x.dataset.id);}));renderTrace();}
function openRecord(id){const r=state.records.find(x=>x.id===id);if(!r)return;const sections=[];if(r.description)sections.push(`<div class="detail-section"><h4>Description</h4><p>${esc(r.description)}</p></div>`);for(const key of ['start','end','date_precision','date_system','region_ids','civilization_ids','source_ids','evidence_ids','subject_ids','comparison_type','interpretation','claim','question','method','result','outcome','notes'])if(r[key]!==undefined&&r[key]!==null&&r[key]!==''&&(!Array.isArray(r[key])||r[key].length))sections.push(`<div class="detail-section"><h4>${esc(titleCase(key))}</h4>${Array.isArray(r[key])?`<ul>${r[key].map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:`<p>${esc(r[key])}</p>`}</div>`);$('dialogContent').innerHTML=`<div class="eyebrow">${esc(typeLabel(r.type))}</div><h2 style="margin-top:6px">${esc(r.title||r.id)}</h2><div class="detail-meta">${chips(r)}<span class="chip">${esc(r.version||'')}</span></div>${sections.join('')}<div class="trace-actions"><button class="graph-btn" id="traceRecord">Trace this record →</button></div><pre class="json-preview">${esc(JSON.stringify(r,null,2))}</pre><p class="muted" style="margin-top:9px"><a style="color:var(--accent)" href="${esc(r._url||'#')}" target="_blank" rel="noopener">Open canonical record on GitHub ↗</a></p>`;$('recordDialog').showModal();$('traceRecord').addEventListener('click',()=>{$('recordDialog').close();runTrace(id);});}
function switchView(view){state.activeView=view;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(`${view}View`).classList.add('active');if(view==='graph')renderGraph();if(view==='intelligence')renderIntelligence();}
function resetGraph(){state.graphZoom=1;state.graphPanX=0;state.graphPanY=0;state.selectedId=null;renderGraph();}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$('search').addEventListener('input',applyFilters);$('typeFilter').addEventListener('change',applyFilters);$('statusFilter').addEventListener('change',applyFilters);$('confidenceFilter').addEventListener('change',applyFilters);$('closeDialog').addEventListener('click',()=>$('recordDialog').close());$('recordDialog').addEventListener('click',e=>{if(e.target===$('recordDialog'))$('recordDialog').close();});$('resetGraph')?.addEventListener('click',resetGraph);$('traceSelected')?.addEventListener('click',()=>{if(state.selectedId)runTrace(state.selectedId);});loadDataset().catch(e=>{$('status').textContent='Dataset connection failed';$('recordGrid').innerHTML=`<div class="record-card"><h3>Could not load the canonical dataset</h3><p>${esc(e.message)}</p></div>`;});