(() => {
  const API='https://api.github.com/repos/jawa-dam/GEI-Research/contents/data';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const get=async path=>{const r=await fetch(`${API}${path?`/${path}`:''}?ref=main`,{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw new Error(`${r.status}`);return r.json()};
  const load=async path=>{const files=await get(path);return Promise.all(files.filter(x=>x.type==='file'&&x.name.endsWith('.json')).map(async f=>{try{return await (await fetch(f.download_url)).json()}catch{return null}}));};
  const loadAll=async()=>{const roots=await get('');const dirs=roots.filter(x=>x.type==='dir').map(x=>x.name);const groups=await Promise.all(dirs.map(async d=>{try{return await load(d)}catch{return[]}}));return groups.flat().filter(Boolean);};
  const canonicalize=v=>{if(Array.isArray(v))return `[${v.map(canonicalize).join(',')}]`;if(v&&typeof v==='object')return `{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonicalize(v[k])}`).join(',')}}`;return JSON.stringify(v)};
  async function sha256(value){const bytes=new TextEncoder().encode(canonicalize(value));const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('');}
  function install(){const view=document.getElementById('provenanceView');if(!view||document.getElementById('integrityAttestationPanel'))return;const s=document.createElement('section');s.id='integrityAttestationPanel';s.style.marginTop='22px';s.innerHTML=`<div class="section-heading"><div><span class="eyebrow">V1.0.13 · INTEGRITY ATTESTATION</span><h2>Provenance Drift Detection</h2></div><span id="integrityStatus" class="muted">Computing…</span></div><div class="provenance-banner"><strong>CANONICAL RECORD → BASELINE DIGEST → CURRENT DIGEST → DRIFT DETECTION → ATTESTATION</strong><p>A SHA-256 digest detects silent content changes relative to a recorded baseline. A match demonstrates content stability only; it does not establish truth, authorial intent, or evidentiary sufficiency.</p></div><div id="integritySummary" class="audit-summary"></div><div id="integrityGrid" class="provenance-grid"></div><div class="trail-scroll" id="attestationLedger"></div>`;view.appendChild(s);}
  async function init(){install();try{const [records,provenance,attestations]=await Promise.all([loadAll(),load('provenance'),load('attestations')]);const byId=new Map(records.map(r=>[r.id,r]));const baselines=provenance.filter(p=>p&&p.record_digests&&p.verification_status==='verified');const latest=new Map();baselines.forEach(p=>(p.record_ids||[]).forEach(id=>{if(!latest.has(id)||String(p.timestamp)>String(latest.get(id).timestamp))latest.set(id,p)}));const results=[];for(const [id,p] of latest){const r=byId.get(id);if(!r){results.push({id,status:'fail',expected:p.record_digests[id]||'',observed:'',baseline:p.id});continue}const observed=await sha256(r),expected=p.record_digests[id],status=observed===expected?'pass':'drift';results.push({id,status,expected,observed,baseline:p.id});}
    const drift=results.filter(x=>x.status==='drift'),fail=results.filter(x=>x.status==='fail');document.getElementById('integrityStatus').textContent=`${results.length-drift.length-fail.length} stable · ${drift.length} drift · ${fail.length} missing`;
    document.getElementById('integritySummary').innerHTML=[['CHECKED',results.length],['STABLE',results.filter(x=>x.status==='pass').length],['DRIFT',drift.length],['FAIL',fail.length]].map(x=>`<div class="audit-stat"><strong>${x[1]}</strong><span>${x[0]}</span></div>`).join('');
    document.getElementById('integrityGrid').innerHTML=results.length?results.map(x=>`<article class="provenance-card"><div class="chips"><span class="chip ${x.status==='pass'?'good':x.status==='drift'?'warn':'hyp'}">${x.status.toUpperCase()}</span><span class="chip">${esc(x.baseline)}</span></div><h3>${esc(x.id)}</h3><p>${x.status==='pass'?'Current canonical content matches the verified baseline.':x.status==='drift'?'Current canonical content differs from the verified baseline. A new provenance event is required to explain the change.':'The baseline target cannot be resolved.'}</p><small>Expected: ${esc(x.expected)}<br>Observed: ${esc(x.observed)}</small></article>`).join(''):'<div class="record-card"><p>No digest baselines available.</p></div>';
    document.getElementById('attestationLedger').innerHTML=attestations.length?`<table class="trail-table"><thead><tr><th>Attestation</th><th>Status</th><th>Baseline</th><th>Records</th><th>Checked</th></tr></thead><tbody>${attestations.sort((a,b)=>String(b.checked_at).localeCompare(String(a.checked_at))).map(a=>`<tr><td>${esc(a.id)}<small>${esc(a.title)}</small></td><td><span class="audit-status-${a.attestation_status==='pass'?'pass':a.attestation_status==='warn'?'warn':'fail'}">${esc(a.attestation_status)}</span></td><td>${esc(a.baseline_provenance_id)}</td><td>${esc((a.record_ids||[]).join(', '))}</td><td>${esc(a.checked_at||'')}</td></tr>`).join('')}</tbody></table>`:'<div class="record-card"><p>No canonical attestation records loaded.</p></div>';
  }catch(e){const s=document.getElementById('integrityStatus');if(s)s.textContent='Integrity check unavailable';const g=document.getElementById('integrityGrid');if(g)g.innerHTML=`<div class="record-card"><p>Integrity attestation could not load: ${esc(e.message)}</p></div>`;}}
  window.__integrityEngine={init,sha256};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
