(() => {
  const API='https://api.github.com/repos/jawa-dam/GEI-Research/contents/data';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const get=async path=>{const r=await fetch(`${API}/${path}?ref=main`,{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw new Error(`${r.status}`);return r.json()};
  const load=async path=>{const files=await get(path);return Promise.all(files.filter(x=>x.type==='file'&&x.name.endsWith('.json')).map(async f=>{try{return await (await fetch(f.download_url)).json()}catch{return null}}))};
  const css=document.createElement('style');css.textContent='.outcome-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px}.outcome-card,.evaluation-card{padding:20px;border:1px solid rgba(255,255,255,.1);border-radius:16px;background:rgba(255,255,255,.04);cursor:pointer}.outcome-card:hover,.evaluation-card:hover{transform:translateY(-2px)}.outcome-banner{margin:16px 0;padding:18px;border-radius:16px;background:linear-gradient(135deg,rgba(0,77,97,.35),rgba(255,64,129,.16))}.outcome-flow{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.outcome-stage{padding:9px 12px;border-radius:999px;background:rgba(255,255,255,.07);font-size:.82rem}.outcome-stage.active{outline:1px solid rgba(255,255,255,.35)}.outcome-workspace{margin-top:20px}.delta-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px;margin-top:14px}.delta-box{padding:14px;border-radius:12px;background:rgba(255,255,255,.045)}.delta-box h4{margin:0 0 7px}.outcome-disposition{font-weight:700}.outcome-muted{opacity:.72}@media(max-width:700px){.outcome-grid{grid-template-columns:1fr}}';document.head.appendChild(css);
  function installView(){
    const nav=document.querySelector('.tabs'),main=document.querySelector('main'); if(!nav||!main)return;
    if(document.querySelector('[data-view="outcomes"]'))return;
    const tab=document.createElement('button');tab.className='tab';tab.dataset.view='outcomes';tab.textContent='Outcome Intelligence';nav.appendChild(tab);
    const section=document.createElement('section');section.id='outcomesView';section.className='view';section.innerHTML=`<div class="section-heading"><div><span class="eyebrow">V1.0.11 · OUTCOME INTELLIGENCE</span><h2>Research Outcome Intelligence</h2></div><span id="outcomeCount" class="muted">Loading…</span></div><div class="outcome-banner"><strong>RESULT → OUTCOME → EVALUATION → HYPOTHESIS REVISION</strong><p>Compare expected and observed states, identify the evidence gap, and record whether the outcome supports, challenges, or remains inconclusive. The engine never promotes a hypothesis automatically.</p></div><div id="outcomeGrid" class="outcome-grid"></div><div class="outcome-workspace panel"><div class="workspace-head"><div><span class="eyebrow">ACTIVE OUTCOME</span><h2 id="outcomeTitle">Select an outcome</h2></div><span id="outcomeStatus" class="chip">—</span></div><div id="outcomeFlow" class="outcome-flow"></div><div class="delta-grid"><div class="delta-box"><h4>Expected</h4><p id="expectedState" class="outcome-muted">—</p></div><div class="delta-box"><h4>Observed</h4><p id="observedState" class="outcome-muted">—</p></div><div class="delta-box"><h4>Delta / Evidence Gap</h4><p id="outcomeDelta" class="outcome-muted">—</p></div></div><div class="workspace-notes"><div><span class="eyebrow">ASSESSMENT</span><p id="outcomeAssessment">Select an outcome to inspect its evaluation.</p></div><div><span class="eyebrow">REVISION / NEXT STEPS</span><p id="revisionRecommendation">—</p><ul id="outcomeNextSteps"></ul></div></div></div>`;main.appendChild(section);
    tab.addEventListener('click',()=>window.__switchView&&window.__switchView('outcomes'));
    return section;
  }
  let outcomes=[],evaluations=[],results=[],active=null;
  const find=id=>[...outcomes,...evaluations,...results].find(x=>x&&x.id===id);
  function render(){const grid=document.getElementById('outcomeGrid');if(!grid)return;document.getElementById('outcomeCount').textContent=`${outcomes.length} outcome${outcomes.length===1?'':'s'} · ${evaluations.length} evaluation${evaluations.length===1?'':'s'}`;grid.innerHTML=outcomes.length?outcomes.map(o=>{const ev=evaluations.find(e=>(e.outcome_ids||[]).includes(o.id));return`<article class="outcome-card" data-id="${esc(o.id)}"><div class="chips"><span class="chip type">Outcome</span><span class="chip">${esc(o.disposition||'unclassified')}</span>${o.confidence?`<span class="chip">${esc(o.confidence)}</span>`:''}</div><h3>${esc(o.title||o.id)}</h3><p>${esc(o.outcome||'')}</p><small>${ev?`Evaluation: ${esc(ev.evaluation_status)}`:'No evaluation linked'}</small></article>`}).join(''):'<div class="record-card"><p>No outcome records loaded.</p></div>';grid.querySelectorAll('[data-id]').forEach(x=>x.addEventListener('click',()=>select(x.dataset.id)));}
  function select(id){active=outcomes.find(o=>o.id===id);if(!active)return;const ev=evaluations.find(e=>(e.outcome_ids||[]).includes(id));const res=results.find(r=>(active.result_ids||[]).includes(r.id));document.getElementById('outcomeTitle').textContent=active.title||active.id;document.getElementById('outcomeStatus').textContent=active.disposition||active.status||'—';document.getElementById('expectedState').textContent=ev?.expected_state||'No expected state recorded.';document.getElementById('observedState').textContent=ev?.observed_state||res?.result||'No observed state recorded.';document.getElementById('outcomeDelta').textContent=ev?.delta||'No delta recorded.';document.getElementById('outcomeAssessment').textContent=ev?.assessment||active.outcome||'No assessment recorded.';document.getElementById('revisionRecommendation').textContent=ev?.revision_recommendation||'No revision recommendation recorded.';document.getElementById('outcomeNextSteps').innerHTML=(active.next_steps||[]).map(x=>`<li>${esc(x)}</li>`).join('');document.getElementById('outcomeFlow').innerHTML=['RESULT','OUTCOME','EVALUATION','HYPOTHESIS REVISION'].map((x,i)=>`<span class="outcome-stage ${i===1?'active':''}">${x}</span>`).join('');}
  async function init(){installView();try{[outcomes,evaluations,results]=await Promise.all([load('outcomes'),load('evaluations'),load('results')]);outcomes=outcomes.filter(Boolean);evaluations=evaluations.filter(Boolean);results=results.filter(Boolean);render();}catch(e){const c=document.getElementById('outcomeGrid');if(c)c.innerHTML=`<div class="record-card"><p>Outcome intelligence could not load: ${esc(e.message)}</p></div>`;}}
  window.__outcomeEngine={init,select};
  const originalSwitch=window.switchView;window.__switchView=originalSwitch||((view)=>{document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===view));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`${view}View`));});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
