(() => {
  const API='https://api.github.com/repos/jawa-dam/GEI-Research/contents/data';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const get=async path=>{const r=await fetch(`${API}/${path}?ref=main`,{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw new Error(`${r.status}`);return r.json()};
  const load=async path=>{const files=await get(path);return Promise.all(files.filter(x=>x.type==='file'&&x.name.endsWith('.json')).map(async f=>{try{return await (await fetch(f.download_url)).json()}catch{return null}}))};
  const css=document.createElement('style');css.textContent='.provenance-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px}.provenance-card{padding:20px;border:1px solid rgba(255,255,255,.1);border-radius:16px;background:rgba(255,255,255,.04);cursor:pointer}.provenance-card:hover{transform:translateY(-2px)}.provenance-banner{margin:16px 0;padding:18px;border-radius:16px;background:linear-gradient(135deg,rgba(0,77,97,.35),rgba(255,64,129,.16))}.provenance-meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;margin-top:16px}.provenance-box{padding:14px;border-radius:12px;background:rgba(255,255,255,.045)}.provenance-box h4{margin:0 0 7px}.provenance-muted{opacity:.72}@media(max-width:700px){.provenance-grid{grid-template-columns:1fr}}';document.head.appendChild(css);
  function installView(){const nav=document.querySelector('.tabs'),main=document.querySelector('main');if(!nav||!main||document.querySelector('[data-view="provenance"]'))return;const tab=document.createElement('button');tab.className='tab';tab.dataset.view='provenance';tab.textContent='Integrity & Provenance';nav.appendChild(tab);const section=document.createElement('section');section.id='provenanceView';section.className='view';section.innerHTML=`<div class="section-heading"><div><span class="eyebrow">V1.0.12 · RESEARCH INTEGRITY</span><h2>Integrity & Provenance Engine</h2></div><span id="provenanceCount" class="muted">Loading…</span></div><div class="provenance-banner"><strong>WHO → WHAT → WHEN → WHY → VERSION → VERIFICATION</strong><p>Trace research record history and verification state without treating provenance as substantive evidence. Provenance explains the research record; it does not prove the interpretation.</p></div><div id="provenanceGrid" class="provenance-grid"></div><div class="workspace panel"><div class="workspace-head"><div><span class="eyebrow">PROVENANCE INSPECTOR</span><h2 id="provenanceTitle">Select a provenance event</h2></div><span id="provenanceStatus" class="chip">—</span></div><div class="provenance-meta"><div class="provenance-box"><h4>Event</h4><p id="provEvent">—</p></div><div class="provenance-box"><h4>Records</h4><p id="provRecords">—</p></div><div class="provenance-box"><h4>Actor / Time</h4><p id="provActor">—</p></div><div class="provenance-box"><h4>Verification</h4><p id="provVerification">—</p></div></div><div class="workspace-notes"><div><span class="eyebrow">WHY IT CHANGED / WAS VERIFIED</span><p id="provReason">—</p></div><div><span class="eyebrow">INTEGRITY NOTES</span><p id="provNotes" class="provenance-muted">—</p></div></div></div>`;main.appendChild(section);tab.addEventListener('click',()=>window.__switchView&&window.__switchView('provenance'));return section;}
  let records=[];function render(){const grid=document.getElementById('provenanceGrid');if(!grid)return;document.getElementById('provenanceCount').textContent=`${records.length} provenance event${records.length===1?'':'s'}`;grid.innerHTML=records.length?records.map(p=>`<article class="provenance-card" data-id="${esc(p.id)}"><div class="chips"><span class="chip type">${esc(p.event_type)}</span><span class="chip">${esc(p.verification_status)}</span></div><h3>${esc(p.title||p.id)}</h3><p>${esc(p.reason)}</p><small>${esc((p.record_ids||[]).join(' · '))}</small></article>`).join(''):'<div class="record-card"><p>No provenance records loaded.</p></div>';grid.querySelectorAll('[data-id]').forEach(x=>x.addEventListener('click',()=>select(x.dataset.id)));}
  function select(id){const p=records.find(x=>x.id===id);if(!p)return;document.getElementById('provenanceTitle').textContent=p.title||p.id;document.getElementById('provenanceStatus').textContent=p.status||'—';document.getElementById('provEvent').textContent=p.event_type||'—';document.getElementById('provRecords').textContent=(p.record_ids||[]).join(', ')||'—';document.getElementById('provActor').textContent=`${p.actor||'—'} · ${p.timestamp||'—'}`;document.getElementById('provVerification').textContent=p.verification_status||'—';document.getElementById('provReason').textContent=p.reason||'—';document.getElementById('provNotes').textContent=p.integrity_notes||'No integrity notes recorded.';}
  async function init(){installView();try{records=(await load('provenance')).filter(Boolean);render();}catch(e){const c=document.getElementById('provenanceGrid');if(c)c.innerHTML=`<div class="record-card"><p>Provenance engine could not load: ${esc(e.message)}</p></div>`;}}
  window.__provenanceEngine={init,select};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
