/* GEI Research V1.0.16 — Independent Replication & Cross-Operator Verification Engine */
(function(){
const base=window.GEI_BASE||'';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function get(path){const r=await fetch(base+path,{cache:'no-store'});if(!r.ok)throw new Error(path+' '+r.status);return r.json()}
async function load(){
const host=document.querySelector('#decisionsView')||document.querySelector('main');if(!host||document.querySelector('#replicationPanel'))return;
const panel=document.createElement('section');panel.id='replicationPanel';panel.className='panel';
panel.innerHTML='<div class="section-heading"><div><span class="eyebrow">V1.0.16 · REPLICATION</span><h2>Independent Replication & Cross-Operator Verification</h2></div><span class="chip">BASELINE</span></div><div id="replicationBody" class="workspace-notes"><p class="muted">Loading canonical replication framework…</p></div>';host.appendChild(panel);
try{
const [p,r]=await Promise.all([get('data/protocols/PRO-GEI-V1015-001.json'),get('data/replications/RPL-GEI-V1016-001.json')]);
const independent=(r.operators||[]).filter(o=>o.independent),runs=r.replication_runs||[],cmp=r.comparison||{};
document.querySelector('#replicationBody').innerHTML=`<div class="firewall"><div class="flow"><span>BASELINE</span><b>→</b><span>OPERATOR A</span><b>→</b><span>OPERATOR B</span><b>→</b><span>BLIND COMPARISON</span><b>→</b><span>REPLICATION RESULT</span></div><p>Cross-operator agreement tests repeatability of the research procedure. It does not turn agreement into proof of the GEI interpretation.</p></div><div class="workspace-notes"><div><span class="eyebrow">REPLICATION OBJECTIVE</span><p>Run the same V1.0.15 protocol independently, preserve deviations and disagreements, then compare operator outputs without silently averaging away differences.</p><span class="eyebrow">PROTOCOL</span><p><strong>${esc(p.id)}</strong> · version ${esc(p.version)}</p></div><div><span class="eyebrow">INDEPENDENT OPERATORS</span><ul>${independent.map(o=>`<li><strong>${esc(o.operator_id)}</strong> — ${esc(o.role)} · ${esc(o.status)}</li>`).join('')}</ul><p class="muted">At least two independent operators are required before replication can be classified as replicated.</p></div></div><div class="workspace-notes"><div><span class="eyebrow">RUN STATUS</span><ul>${runs.map(x=>`<li><strong>${esc(x.run_id)}</strong> — ${esc(x.operator_id)} · ${esc(x.status)}${x.blind_to_baseline?' · blind':''}</li>`).join('')}</ul></div><div><span class="eyebrow">CROSS-OPERATOR COMPARISON</span><p><strong>${esc(cmp.comparison_status)}</strong></p><ul>${Object.entries(cmp.agreement_metrics||{}).map(([k,v])=>`<li>${esc(k)}: ${Math.round(Number(v)*100)}%</li>`).join('')}</ul><p>${esc(cmp.resolution_method)}</p></div></div><div class="workspace-notes"><div><span class="eyebrow">CURRENT REPLICATION STATE</span><p><strong>${esc(r.replication_status)}</strong> · score ${esc(r.replication_score)}</p><p>${esc((r.deviations||[]).join(' '))}</p></div><div><span class="eyebrow">EPISTEMIC FIREWALL</span><p>${esc(r.epistemic_firewall)}</p></div></div>`;
}catch(e){document.querySelector('#replicationBody').innerHTML='<p class="muted">Replication data could not be loaded.</p>';console.error(e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load);else load();})();
